---
- name: Setup Munge and Slurm on master node and compute nodes
  hosts: all
  become: yes
  vars:
    munge_key_path: /etc/munge/munge.key
    slurm_conf_path: /etc/slurm/slurm.conf
    cgroup_conf_path: /etc/slurm/cgroup.conf
    slurm_user: slurm
    slurm_group: slurm
    # slurm_version: 20.11.7  # Adjust this to the desired Slurm version
  tasks:

    - name: Install necessary packages for controller node
      apt:
        name:
          - munge
          - slurm-wlm
        state: present
      when: inventory_hostname == "nilkhan-master"

    - name: Install necessary packages for compute node
      apt:
        name:
          - munge
          - slurm-client
        state: present
      when: "'nilkhan_compute' in group_names"
  

    - name: Ensure Munge key directory exists
      file:
        path: /etc/munge
        state: directory
        owner: munge
        group: munge
        mode: '0700'

    - name: Get Munge key content from master
      fetch:
        src: "{{ munge_key_path }}"
        dest: "{{ inventory_dir }}/files{{ munge_key_path }}"
        flat: yes
      when: inventory_hostname == "nilkhan-master"

    - name: Deploy Munge key to nodes
      copy:
        src: "{{ inventory_dir }}/files/etc/munge/munge.key"
        dest: "{{ munge_key_path }}"
        owner: munge
        group: munge
        mode: '0400'
      when: "'nilkhan_compute' in group_names"

    - name: Ensure Munge service is enabled and started
      service:
        name: munge
        state: started
        enabled: yes

    - name: Ensure Slurm user and group exist
      user:
        name: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        state: present
        system: yes

    - name: Ensure Slurm configuration directory exists
      file:
        path: /etc/slurm
        state: directory
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0755'


    - name: Deploy slurm config to all nodes
      copy:
        src: "{{ inventory_dir }}/files{{ slurm_conf_path }}"
        dest: "{{ slurm_conf_path }}"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0444'
      
    - name: Deploy cgroup conf for slurm to all nodes
      copy:
        src: "{{ inventory_dir }}/files{{ cgroup_conf_path }}"
        dest: "{{ cgroup_conf_path }}"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0400'

    - name: Ensure Slurm service is enabled and started on master node
      service:
        name: slurmctld
        state: started
        enabled: yes
      when: inventory_hostname == 'nilkhan-master'
 

    - name: Ensure Slurm service is enabled and started on all nodes
      service:
        name: slurmd
        state: started
        enabled: yes

    - name: Reboot the system
      ansible.builtin.reboot:
        # test_command: uptime
        # connect_timeout: 30
        # reboot_timeout: 300
        # post_reboot_delay: 10
        # pre_reboot_delay: 10