---
- name: Setup Munge and Slurm on front-end and compute nodes
  hosts: all
  become: yes
  vars:
    munge_key_path: /etc/munge/munge.key
    slurm_conf_path: /etc/slurm-llnl/slurm.conf
    slurm_user: slurm
    slurm_group: slurm
    slurm_version: 20.11.7  # Adjust this to the desired Slurm version
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - munge
          - libmunge-dev
          - slurm-wlm
        state: present

    - name: Ensure Munge key directory exists
      file:
        path: /etc/munge
        state: directory
        owner: munge
        group: munge
        mode: '0700'

    - name: Copy Munge key to all nodes
      copy:
        src: "{{ munge_key_path }}"
        dest: "{{ munge_key_path }}"
        owner: munge
        group: munge
        mode: '0400'
      delegate_to: front-end  # Ensure the Munge key is copied from the front-end node

    - name: Ensure Munge service is enabled and started
      service:
        name: munge
        state: started
        enabled: yes

    - name: Ensure Slurm user and group exist
      user:
        name: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        state: present
        system: yes

    - name: Ensure Slurm configuration directory exists
      file:
        path: /etc/slurm-llnl
        state: directory
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0755'

    - name: Copy Slurm configuration file to all nodes
      copy:
        src: "{{ slurm_conf_path }}"
        dest: "{{ slurm_conf_path }}"
        owner: "{{ slurm_user }}"
        group: "{{ slurm_group }}"
        mode: '0644'
      delegate_to: front-end  # Ensure the Slurm configuration is copied from the front-end node

    - name: Ensure Slurm service is enabled and started
      service:
        name: slurmctld
        state: started
        enabled: yes
      when: inventory_hostname == 'front-end'

    - name: Ensure Slurm service is enabled and started on compute nodes
      service:
        name: slurmd
        state: started
        enabled: yes
      when: inventory_hostname != 'front-end'