---
- name: Initial setup for RPI cluster
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - vim
          - git
          - curl
          - btop
          - python3
          - python3-pip
          - sudo
        state: present

