---
- name: Shutdown all nodes in the cluster
  hosts: all
  become: yes
  tasks:
    - name: Shutdown the system
      command: /sbin/shutdown -h now
      async: 1
      poll: 0
      ignore_errors: yes